export interface ICountry{name:string;nameLang:string;code:string;dialCode:string;pattern:RegExp;}
const COUNTRIES:ICountry[]=[
{name:'Afghanistan',nameLang:'افغانستان',code:'af',dialCode:'+93',pattern:/^\d{9}$/},
{name:'Åland Islands',nameLang:'Åland',code:'ax',dialCode:'+358',pattern:/^\d{6,10}$/},
{name:'Albania',nameLang:'Shqipëri',code:'al',dialCode:'+355',pattern:/^\d{9}$/},
{name:'Algeria',nameLang:'الجزائر',code:'dz',dialCode:'+213',pattern:/^\d{9}$/},
{name:'American Samoa',nameLang:'American Samoa',code:'as',dialCode:'+1-684',pattern:/^\d{7}$/},
{name:'Andorra',nameLang:'',code:'ad',dialCode:'+376',pattern:/^\d{6}$/},
{name:'Angola',nameLang:'Angola',code:'ao',dialCode:'+244',pattern:/^\d{9}$/},
{name:'Anguilla',nameLang:'Anguilla',code:'ai',dialCode:'+1-264',pattern:/^\d{7}$/},
{name:'Antigua and Barbuda',nameLang:'',code:'ag',dialCode:'+1-268',pattern:/^\d{9}$/},
{name:'Argentina',nameLang:'Argentina',code:'ar',dialCode:'+54',pattern:/^\d{10,11}$/},
{name:'Armenia',nameLang:'Հայաստան',code:'am',dialCode:'+374',pattern:/^\d{8}$/},
{name:'Aruba',nameLang:'Aruba',code:'aw',dialCode:'+297',pattern:/^\d{7}$/},
{name:'Ascension Island',nameLang:'Ascension Island',code:'ac',dialCode:'+247',pattern:/^\d{5,6}$/},
{name:'Australia',nameLang:'',code:'au',dialCode:'+61',pattern:/^\d{9}$/},
{name:'Austria',nameLang:'Österreich',code:'at',dialCode:'+43',pattern:/^\d{10}$/},
{name:'Azerbaijan',nameLang:'Azərbaycan',code:'az',dialCode:'+994',pattern:/^\d{9}$/},
{name:'Bahamas',nameLang:'',code:'bs',dialCode:'+1-242',pattern:/^\d{9}$/},
{name:'Bahrain',nameLang:'البحرين',code:'bh',dialCode:'+973',pattern:/^\d{8}$/},
{name:'Bangladesh',nameLang:'বাংলাদেশ',code:'bd',dialCode:'+880',pattern:/^\d{10}$/},
{name:'Barbados',nameLang:'',code:'bb',dialCode:'+1-246',pattern:/^\d{9}$/},
{name:'Belarus',nameLang:'Беларусь',code:'by',dialCode:'+375',pattern:/^\d{9}$/},
{name:'Belgium',nameLang:'België',code:'be',dialCode:'+32',pattern:/^\d{9}$/},
{name:'Belize',nameLang:'',code:'bz',dialCode:'+501',pattern:/^\d{7}$/},
{name:'Benin',nameLang:'Bénin',code:'bj',dialCode:'+229',pattern:/^\d{8}$/},
{name:'Bermuda',nameLang:'Bermuda',code:'bm',dialCode:'+1-441',pattern:/^\d{7}$/},
{name:'Bhutan',nameLang:'འབྲུག',code:'bt',dialCode:'+975',pattern:/^\d{8}$/},
{name:'Bolivia',nameLang:'Bolivia',code:'bo',dialCode:'+591',pattern:/^\d{8}$/},
{name:'Bonaire, Sint Eustatius, and Saba',nameLang:'Caribbean Netherlands',code:'bq',dialCode:'+599',pattern:/^\d{7}$/},
{name:'Bosnia and Herzegovina',nameLang:'Bosna i Hercegovina',code:'ba',dialCode:'+387',pattern:/^\d{8,9}$/},
{name:'Botswana',nameLang:'Botswana',code:'bw',dialCode:'+267',pattern:/^\d{8}$/},
{name:'Brazil',nameLang:'Brasil',code:'br',dialCode:'+55',pattern:/^\d{10,11}$/},
{name:'British Indian Ocean Territory',nameLang:'British Indian Ocean Territory',code:'io',dialCode:'+246',pattern:/^3[78]\d{5}$/},
{name:'British Virgin Islands',nameLang:'British Virgin Islands',code:'vg',dialCode:'+1-284',pattern:/^\d{7}$/},
{name:'Brunei',nameLang:'Brunei',code:'bn',dialCode:'+673',pattern:/^\d{7}$/},
{name:'Bulgaria',nameLang:'България',code:'bg',dialCode:'+359',pattern:/^\d{8,9}$/},
{name:'Burkina Faso',nameLang:'Burkina Faso',code:'bf',dialCode:'+226',pattern:/^\d{8}$/},
{name:'Burundi',nameLang:'Burundi',code:'bi',dialCode:'+257',pattern:/^\d{8}$/},
{name:'Cape Verde (Cabo Verde)',nameLang:'Kabu Verdi',code:'cv',dialCode:'+238',pattern:/^\d{7}$/},
{name:'Cambodia',nameLang:'កម្ពុជា',code:'kh',dialCode:'+855',pattern:/^\d{9}$/},
{name:'Cameroon',nameLang:'Cameroun',code:'cm',dialCode:'+237',pattern:/^\d{9}$/},
{name:'Canada',nameLang:'',code:'ca',dialCode:'+1',pattern:/^[2-9]\d{2}[2-9](?!11)\d{6}$/},
{name:'Cayman Islands',nameLang:'Cayman Islands',code:'ky',dialCode:'+1-345',pattern:/^\d{7}$/},
{name:'Central African Republic',nameLang:'République centrafricaine',code:'cf',dialCode:'+236',pattern:/^\d{8}$/},
{name:'Chad',nameLang:'Tchad',code:'td',dialCode:'+235',pattern:/^\d{8}$/},
{name:'Chile',nameLang:'Chile',code:'cl',dialCode:'+56',pattern:/^\d{9}$/},
{name:'China',nameLang:'中国',code:'cn',dialCode:'+86',pattern:/^\d{11}$/},
{name:'Christmas Island',nameLang:'Christmas Island',code:'cx',dialCode:'+61',pattern:/^8\d{8}$/},
{name:'Cocos (Keeling) Islands',nameLang:'Cocos (Keeling) Islands',code:'cc',dialCode:'+61',pattern:/^8\d{8}$/},
{name:'Colombia',nameLang:'Colombia',code:'co',dialCode:'+57',pattern:/^\d{10}$/},
{name:'Comoros',nameLang:'القمُر',code:'km',dialCode:'+269',pattern:/^\d{7}$/},
{name:'Congo',nameLang:'Congo',code:'cg',dialCode:'+242',pattern:/^\d{7,9}$/},
{name:'Congo,Democratic epublic of the',nameLang:'République Démocratique du Congo',code:'cd',dialCode:'+243',pattern:/^\d{9}$/},
{name:'Cook Islands',nameLang:'Cook Islands',code:'ck',dialCode:'+682',pattern:/^\d{5}$/},
{name:'Costa Rica',nameLang:'Costa Rica',code:'cr',dialCode:'+506',pattern:/^\d{8}$/},
{name:"Côte d'Ivoire",nameLang:"Côte d'Ivoire",code:'ci',dialCode:'+225',pattern:/^\d{8}$/},
{name:'Croatia',nameLang:'Hrvatska',code:'hr',dialCode:'+385',pattern:/^\d{9}$/},
{name:'Cuba',nameLang:'Cuba',code:'cu',dialCode:'+53',pattern:/^\d{8}$/},
{name:'Curaçao',nameLang:'Curaçao',code:'cw',dialCode:'+599',pattern:/^\d{7}$/},
{name:'Cyprus',nameLang:'Κύπρος',code:'cy',dialCode:'+357',pattern:/^\d{8}$/},
{name:'Czech Republic',nameLang:'Česká republika',code:'cz',dialCode:'+420',pattern:/^\d{9}$/},
{name:'Denmark',nameLang:'Danmark',code:'dk',dialCode:'+45',pattern:/^\d{8}$/},
{name:'Djibouti',nameLang:'Djibouti',code:'dj',dialCode:'+253',pattern:/^\d{6}$/},
{name:'Dominica',nameLang:'',code:'dm',dialCode:'+1-767',pattern:/^\d{7}$/},
{name:'Dominican Republic',nameLang:'República Dominicana',code:'do',dialCode:'+1-809',pattern:/^\d{7}$/},
{name:'Ecuador',nameLang:'Ecuador',code:'ec',dialCode:'+593',pattern:/^\d{9}$/},
{name:'Egypt',nameLang:'مصر',code:'eg',dialCode:'+20',pattern:/^\d{10}$/},
{name:'El Salvador',nameLang:'El Salvador',code:'sv',dialCode:'+503',pattern:/^\d{8}$/},
{name:'Equatorial Guinea',nameLang:'Guinea Ecuatorial',code:'gq',dialCode:'+240',pattern:/^\d{9}$/},
{name:'Eritrea',nameLang:'ኤርትራ',code:'er',dialCode:'+291',pattern:/^\d{7}$/},
{name:'Estonia',nameLang:'Eesti',code:'ee',dialCode:'+372',pattern:/^\d{7,8}$/},
{name:'Eswatini',nameLang:'eSwatini',code:'sz',dialCode:'+268',pattern:/^\d{8}$/},
{name:'Ethiopia',nameLang:'ኢትዮጵያ',code:'et',dialCode:'+251',pattern:/^\d{9}$/},
{name:'Falkland Islands',nameLang:'Falkland Islands',code:'fk',dialCode:'+500',pattern:/^\d{5}$/},
{name:'Faroe Islands',nameLang:'Føroyar',code:'fo',dialCode:'+298',pattern:/^\d{6}$/},
{name:'Fiji',nameLang:'Fiji',code:'fj',dialCode:'+679',pattern:/^\d{7}$/},
{name:'Finland',nameLang:'Suomi',code:'fi',dialCode:'+358',pattern:/^\d{9}$/},
{name:'France',nameLang:'France',code:'fr',dialCode:'+33',pattern:/^\d{9}$/},
{name:'French Guiana',nameLang:'Guyane française',code:'gf',dialCode:'+594',pattern:/^\d{9}$/},
{name:'French Polynesia',nameLang:'Polynésie française',code:'pf',dialCode:'+689',pattern:/^\d{6}$/},
{name:'Gabon',nameLang:'Gabon',code:'ga',dialCode:'+241',pattern:/^\d{7}$/},
{name:'Gambia',nameLang:'Gambia',code:'gm',dialCode:'+220',pattern:/^\d{7}$/},
{name:'Georgia',nameLang:'საქართველო',code:'ge',dialCode:'+995',pattern:/^\d{9}$/},
{name:'Germany',nameLang:'Deutschland',code:'de',dialCode:'+49',pattern:/^\d{10,11}$/},
{name:'Ghana',nameLang:'Ghana',code:'gh',dialCode:'+233',pattern:/^\d{9}$/},
{name:'Gibraltar',nameLang:'Gibraltar',code:'gi',dialCode:'+350',pattern:/^\d{8}$/},
{name:'Greece',nameLang:'Ελλάδα',code:'gr',dialCode:'+30',pattern:/^\d{10}$/},
{name:'Greenland',nameLang:'Kalaallit Nunaat',code:'gl',dialCode:'+299',pattern:/^\d{6}$/},
{name:'Grenada',nameLang:'',code:'gd',dialCode:'+1-473',pattern:/^\d{7}$/},
{name:'Guadeloupe',nameLang:'Guadeloupe',code:'gp',dialCode:'+590',pattern:/^\d{9}$/},
{name:'Guam',nameLang:'Guam',code:'gu',dialCode:'+1-671',pattern:/^\d{7}$/},
{name:'Guatemala',nameLang:'Guatemala',code:'gt',dialCode:'+502',pattern:/^\d{8}$/},
{name:'Guernsey',nameLang:'Guernsey',code:'gg',dialCode:'+44',pattern:/^1481\d{6}$/},
{name:'Guinea',nameLang:'Guinée',code:'gn',dialCode:'+224',pattern:/^\d{9}$/},
{name:'Guinea-Bissau',nameLang:'Guiné-Bissau',code:'gw',dialCode:'+245',pattern:/^\d{7}$/},
{name:'Guyana',nameLang:'Guyana',code:'gy',dialCode:'+592',pattern:/^\d{7}$/},
{name:'Haiti',nameLang:'Haïti',code:'ht',dialCode:'+509',pattern:/^\d{8}$/},
{name:'Honduras',nameLang:'Honduras',code:'hn',dialCode:'+504',pattern:/^\d{8}$/},
{name:'Hong Kong',nameLang:'香港',code:'hk',dialCode:'+852',pattern:/^\d{8}$/},
{name:'Hungary',nameLang:'Magyarország',code:'hu',dialCode:'+36',pattern:/^\d{9}$/},
{name:'Iceland',nameLang:'Ísland',code:'is',dialCode:'+354',pattern:/^\d{7}$/},
{name:'India',nameLang:'भारत',code:'in',dialCode:'+91',pattern:/^\d{10}$/},
{name:'Indonesia',nameLang:'Indonesia',code:'id',dialCode:'+62',pattern:/^\d{10,13}$/},
{name:'Iran',nameLang:'ایران',code:'ir',dialCode:'+98',pattern:/^\d{11}$/},
{name:'Iraq',nameLang:'العراق',code:'iq',dialCode:'+964',pattern:/^\d{10}$/},
{name:'Ireland',nameLang:'Éire',code:'ie',dialCode:'+353',pattern:/^\d{7,10}$/},
{name:'Isle of Man',nameLang:'Isle of Man',code:'im',dialCode:'+44',pattern:/^1624\d{6}$/},
{name:'Israel',nameLang:'ישראל',code:'il',dialCode:'+972',pattern:/^\d{9}$/},
{name:'Italy',nameLang:'Italia',code:'it',dialCode:'+39',pattern:/^\d{10}$/},
{name:'Jamaica',nameLang:'',code:'jm',dialCode:'+1-876',pattern:/^\d{7}$/},
{name:'Japan',nameLang:'日本',code:'jp',dialCode:'+81',pattern:/^\d{10,11}$/},
{name:'Jersey',nameLang:'Jersey',code:'je',dialCode:'+44',pattern:/^1534\d{6}$/},
{name:'Jordan',nameLang:'الأردن',code:'jo',dialCode:'+962',pattern:/^\d{9}$/},
{name:'Kazakhstan',nameLang:'Қазақстан',code:'kz',dialCode:'+7',pattern:/^\d{10}$/},
{name:'Kenya',nameLang:'Kenya',code:'ke',dialCode:'+254',pattern:/^\d{10}$/},
{name:'Kiribati',nameLang:'Kiribati',code:'ki',dialCode:'+686',pattern:/^\d{7}$/},
{name:'Kosovo',nameLang:'Kosovë',code:'xk',dialCode:'+383',pattern:/^\d{8}$/},
{name:'Kuwait',nameLang:'الكويت',code:'kw',dialCode:'+965',pattern:/^\d{8}$/},
{name:'Kyrgyzstan',nameLang:'Кыргызстан',code:'kg',dialCode:'+996',pattern:/^\d{9}$/},
{name:'Laos',nameLang:'ລາວ',code:'la',dialCode:'+856',pattern:/^\d{8}$/},
{name:'Latvia',nameLang:'Latvija',code:'lv',dialCode:'+371',pattern:/^\d{8}$/},
{name:'Lebanon',nameLang:'لبنان',code:'lb',dialCode:'+961',pattern:/^\d{8}$/},
{name:'Lesotho',nameLang:'Lesotho',code:'ls',dialCode:'+266',pattern:/^\d{8}$/},
{name:'Liberia',nameLang:'Liberia',code:'lr',dialCode:'+231',pattern:/^\d{7}$/},
{name:'Libya',nameLang:'ليبيا',code:'ly',dialCode:'+218',pattern:/^\d{9}$/},
{name:'Liechtenstein',nameLang:'Liechtenstein',code:'li',dialCode:'+423',pattern:/^\d{8}$/},
{name:'Lithuania',nameLang:'Lietuva',code:'lt',dialCode:'+370',pattern:/^\d{8,9}$/},
{name:'Luxembourg',nameLang:'Luxembourg',code:'lu',dialCode:'+352',pattern:/^\d{6,9}$/},
{name:'Macau',nameLang:'澳門',code:'mo',dialCode:'+853',pattern:/^\d{8}$/},
{name:'Madagascar',nameLang:'Madagasikara',code:'mg',dialCode:'+261',pattern:/^\d{9}$/},
{name:'Malawi',nameLang:'Malawi',code:'mw',dialCode:'+265',pattern:/^\d{9}$/},
{name:'Malaysia',nameLang:'Malaysia',code:'my',dialCode:'+60',pattern:/^\d{10,11}$/},
{name:'Maldives',nameLang:'ދިވެހި',code:'mv',dialCode:'+960',pattern:/^\d{7}$/},
{name:'Mali',nameLang:'Mali',code:'ml',dialCode:'+223',pattern:/^\d{8}$/},
{name:'Malta',nameLang:'Malta',code:'mt',dialCode:'+356',pattern:/^\d{8}$/},
{name:'Marshall Islands',nameLang:'',code:'mh',dialCode:'+692',pattern:/^\d{7}$/},
{name:'Martinique',nameLang:'Martinique',code:'mq',dialCode:'+596',pattern:/^\d{9}$/},
{name:'Mauritania',nameLang:'المرس',code:'mr',dialCode:'+222',pattern:/^\d{8}$/},
{name:'Mauritius',nameLang:'Maurice',code:'mu',dialCode:'+230',pattern:/^\d{8}$/},
{name:'Mayotte',nameLang:'Mayotte',code:'yt',dialCode:'+262',pattern:/^\d{9}$/},
{name:'Mexico',nameLang:'México',code:'mx',dialCode:'+52',pattern:/^\d{10}$/},
{name:'Micronesia',nameLang:'Federated States of Micronesia',code:'fm',dialCode:'+691',pattern:/^\d{7}$/},
{name:'Moldova',nameLang:'Moldova',code:'md',dialCode:'+373',pattern:/^\d{8}$/},
{name:'Monaco',nameLang:'Monaco',code:'mc',dialCode:'+377',pattern:/^\d{8}$/},
{name:'Mongolia',nameLang:'Монгол Улс',code:'mn',dialCode:'+976',pattern:/^\d{8}$/},
{name:'Montenegro',nameLang:'Crna Gora',code:'me',dialCode:'+382',pattern:/^\d{8}$/},
{name:'Montserrat',nameLang:'Montserrat',code:'ms',dialCode:'+1-664',pattern:/^\d{7}$/},
{name:'Morocco',nameLang:'المغرب',code:'ma',dialCode:'+212',pattern:/^\d{10}$/},
{name:'Mozambique',nameLang:'Moçambique',code:'mz',dialCode:'+258',pattern:/^\d{9}$/},
{name:'Myanmar (Burma)',nameLang:'မြန်မာ',code:'mm',dialCode:'+95',pattern:/^\d{7,9}$/},
{name:'Namibia',nameLang:'Namibia',code:'na',dialCode:'+264',pattern:/^\d{7,9}$/},
{name:'Nauru',nameLang:'Nauru',code:'nr',dialCode:'+674',pattern:/^\d{7}$/},
{name:'Nepal',nameLang:'नेपाल',code:'np',dialCode:'+977',pattern:/^\d{10}$/},
{name:'Netherlands',nameLang:'Nederland',code:'nl',dialCode:'+31',pattern:/^\d{9}$/},
{name:'New Caledonia',nameLang:'Nouvelle-Calédonie',code:'nc',dialCode:'+687',pattern:/^\d{6}$/},
{name:'New Zealand',nameLang:'New Zealand',code:'nz',dialCode:'+64',pattern:/^\d{9}$/},
{name:'Nicaragua',nameLang:'Nicaragua',code:'ni',dialCode:'+505',pattern:/^\d{8}$/},
{name:'Niger',nameLang:'Niger',code:'ne',dialCode:'+227',pattern:/^\d{8}$/},
{name:'Nigeria',nameLang:'Nigeria',code:'ng',dialCode:'+234',pattern:/^\d{10}$/},
{name:'Niue',nameLang:'Niue',code:'nu',dialCode:'+683',pattern:/^\d{4}$/},
{name:'Norfolk Island',nameLang:'Norfolk Island',code:'nf',dialCode:'+672',pattern:/^\d{5}$/},
{name:'North Korea',nameLang:'조선',code:'kp',dialCode:'+850',pattern:/^\d{8}$/},
{name:'North Macedonia',nameLang:'Северна Македонија',code:'mk',dialCode:'+389',pattern:/^\d{8}$/},
{name:'Northern Mariana Islands',nameLang:'Northern Mariana Islands',code:'mp',dialCode:'+1-670',pattern:/^\d{7}$/},
{name:'Norway',nameLang:'Norge',code:'no',dialCode:'+47',pattern:/^\d{8}$/},
{name:'Oman',nameLang:'عمان',code:'om',dialCode:'+968',pattern:/^\d{8}$/},
{name:'Pakistan',nameLang:'پاکستان',code:'pk',dialCode:'+92',pattern:/^\d{10}$/},
{name:'Palau',nameLang:'Palau',code:'pw',dialCode:'+680',pattern:/^\d{7}$/},
{name:'Palestine',nameLang:'فلسطين',code:'ps',dialCode:'+970',pattern:/^\d{9}$/},
{name:'Panama',nameLang:'Panamá',code:'pa',dialCode:'+507',pattern:/^\d{8}$/},
{name:'Papua New Guinea',nameLang:'Papua New Guinea',code:'pg',dialCode:'+675',pattern:/^\d{10}$/},
{name:'Paraguay',nameLang:'Paraguay',code:'py',dialCode:'+595',pattern:/^\d{9}$/},
{name:'Peru',nameLang:'Perú',code:'pe',dialCode:'+51',pattern:/^\d{9}$/},
{name:'Philippines',nameLang:'Pilipinas',code:'ph',dialCode:'+63',pattern:/^\d{10}$/},
{name:'Pitcairn Islands',nameLang:'Pitcairn Islands',code:'pn',dialCode:'+64',pattern:/^\d{4}$/},
{name:'Poland',nameLang:'Polska',code:'pl',dialCode:'+48',pattern:/^\d{9}$/},
{name:'Portugal',nameLang:'Portugal',code:'pt',dialCode:'+351',pattern:/^\d{9}$/},
{name:'Puerto Rico',nameLang:'Puerto Rico',code:'pr',dialCode:'+1-787',pattern:/^\d{7}$/},
{name:'Qatar',nameLang:'قطر',code:'qa',dialCode:'+974',pattern:/^\d{8}$/},
{name:'Réunion',nameLang:'Réunion',code:'re',dialCode:'+262',pattern:/^\d{9}$/},
{name:'Romania',nameLang:'România',code:'ro',dialCode:'+40',pattern:/^\d{10}$/},
{name:'Russia',nameLang:'Россия',code:'ru',dialCode:'+7',pattern:/^\d{9}$/},
{name:'Rwanda',nameLang:'Rwanda',code:'rw',dialCode:'+250',pattern:/^\d{6}$/},
{name:'Saint Barthélemy',nameLang:'Saint-Barthélemy',code:'bl',dialCode:'+590',pattern:/^\d{9}$/},
{name:'Saint Helena, Ascension, and Tristan da Cunha',nameLang:'Saint Helena',code:'sh',dialCode:'+290',pattern:/^\d{4}$/},
{name:'Saint Kitts and Nevis',nameLang:'',code:'kn',dialCode:'+1-869',pattern:/^\d{6}$/},
{name:'Saint Lucia',nameLang:'',code:'lc',dialCode:'+1-758',pattern:/^\d{6}$/},
{name:'Saint Martin',nameLang:'Saint-Martin',code:'mf',dialCode:'+590',pattern:/^\d{9}$/},
{name:'Saint Pierre and Miquelon',nameLang:'Saint-Pierre-et-Miquelon',code:'pm',dialCode:'+508',pattern:/^\d{6}$/},
{name:'Saint Vincent and the Grenadines',nameLang:'',code:'vc',dialCode:'+1-784',pattern:/^\d{7}$/},
{name:'Samoa',nameLang:'Sāmoa',code:'ws',dialCode:'+685',pattern:/^\d{6,7}$/},
{name:'San Marino',nameLang:'San Marino',code:'sm',dialCode:'+378',pattern:/^\d{6,7}$/},
{name:'Sao Tome and Principe',nameLang:'São Tomé e Príncipe',code:'st',dialCode:'+239',pattern:/^\d{6,7}$/},
{name:'Saudi Arabia',nameLang:'المملكة العربية السعودية',code:'sa',dialCode:'+966',pattern:/^\d{9}$/},
{name:'Senegal',nameLang:'Sénégal',code:'sn',dialCode:'+221',pattern:/^\d{9}$/},
{name:'Serbia',nameLang:'Србија',code:'rs',dialCode:'+381',pattern:/^\d{9,10}$/},
{name:'Seychelles',nameLang:'Seychelles',code:'sc',dialCode:'+248',pattern:/^\d{7}$/},
{name:'Sierra Leone',nameLang:'Sierra Leone',code:'sl',dialCode:'+232',pattern:/^\d{8}$/},
{name:'Singapore',nameLang:'Singapore',code:'sg',dialCode:'+65',pattern:/^\d{8}$/},
{name:'Sint Maarten',nameLang:'Sint Maarten',code:'sx',dialCode:'+1-721',pattern:/^\d{7}$/},
{name:'Slovakia',nameLang:'Slovensko',code:'sk',dialCode:'+421',pattern:/^\d{9}$/},
{name:'Slovenia',nameLang:'Slovenija',code:'si',dialCode:'+386',pattern:/^\d{8}$/},
{name:'Solomon Islands',nameLang:'Solomon Islands',code:'sb',dialCode:'+677',pattern:/^\d{7}$/},
{name:'Somalia',nameLang:'Soomaaliya',code:'so',dialCode:'+252',pattern:/^\d{7,9}$/},
{name:'South Africa',nameLang:'South Africa',code:'za',dialCode:'+27',pattern:/^\d{10}$/},
{name:'South Korea',nameLang:'대한민국',code:'kr',dialCode:'+82',pattern:/^\d{10,11}$/},
{name:'South Sudan',nameLang:'جنوب السودان',code:'ss',dialCode:'+211',pattern:/^\d{9}$/},
{name:'Spain',nameLang:'España',code:'es',dialCode:'+34',pattern:/^\d{9}$/},
{name:'Sri Lanka',nameLang:'ශ්‍රී ලංකාව',code:'lk',dialCode:'+94',pattern:/^\d{10}$/},
{name:'Sudan',nameLang:'السودان',code:'sd',dialCode:'+249',pattern:/^\d{10}$/},
{name:'Suriname',nameLang:'Suriname',code:'sr',dialCode:'+597',pattern:/^\d{7}$/},
{name:'Svalbard & Jan Mayen',nameLang:'Svalbard og Jan Mayen',code:'sj',dialCode:'+47',pattern:/^\d{8}$/},
{name:'Sweden',nameLang:'Sverige',code:'se',dialCode:'+46',pattern:/^\d{10}$/},
{name:'Switzerland',nameLang:'Schweiz',code:'ch',dialCode:'+41',pattern:/^\d{9}$/},
{name:'Syria',nameLang:'سوريا',code:'sy',dialCode:'+963',pattern:/^\d{9}$/},
{name:'Taiwan',nameLang:'台灣',code:'tw',dialCode:'+886',pattern:/^\d{9,10}$/},
{name:'Tajikistan',nameLang:'Тоҷикистон',code:'tj',dialCode:'+992',pattern:/^\d{9}$/},
{name:'Tanzania',nameLang:'Tanzania',code:'tz',dialCode:'+255',pattern:/^\d{10}$/},
{name:'Thailand',nameLang:'ไทย',code:'th',dialCode:'+66',pattern:/^\d{9,10}$/},
{name:'Timor-Leste',nameLang:'Timor-Leste',code:'tl',dialCode:'+670',pattern:/^\d{9}$/},
{name:'Togo',nameLang:'Togo',code:'tg',dialCode:'+228',pattern:/^\d{8}$/},
{name:'Tokelau',nameLang:'Tokelau',code:'tk',dialCode:'+690',pattern:/^\d{4}$/},
{name:'Tonga',nameLang:'Tonga',code:'to',dialCode:'+676',pattern:/^\d{4,5}$/},
{name:'Trinidad and Tobago',nameLang:'',code:'tt',dialCode:'+1-868',pattern:/^\d{6}$/},
{name:'Tunisia',nameLang:'تونس',code:'tn',dialCode:'+216',pattern:/^\d{8}$/},
{name:'Turkey',nameLang:'Türkiye',code:'tr',dialCode:'+90',pattern:/^\d{10}$/},
{name:'Turkmenistan',nameLang:'Türkmenistan',code:'tm',dialCode:'+993',pattern:/^\d{8}$/},
{name:'Turks and Caicos Islands',nameLang:'Turks and Caicos',code:'tc',dialCode:'+1-649',pattern:/^\d{7}$/},
{name:'Tuvalu',nameLang:'Tuvalu',code:'tv',dialCode:'+688',pattern:/^\d{7}$/},
{name:'Uganda',nameLang:'Uganda',code:'ug',dialCode:'+256',pattern:/^\d{9}$/},
{name:'Ukraine',nameLang:'Україна',code:'ua',dialCode:'+380',pattern:/^\d{9,10}$/},
{name:'United Arab Emirates',nameLang:'الإمارات العربية المتحدة',code:'ae',dialCode:'+971',pattern:/^\d{9}$/},
{name:'United Kingdom',nameLang:'United Kingdom',code:'gb',dialCode:'+44',pattern:/^\d{10}$/},
{name:'United States',nameLang:'United States',code:'us',dialCode:'+1',pattern:/^\d{10}$/},
{name:'Uruguay',nameLang:'Uruguay',code:'uy',dialCode:'+598',pattern:/^\d{8}$/},
{name:'Uzbekistan',nameLang:'Oʻzbekiston',code:'uz',dialCode:'+998',pattern:/^\d{9}$/},
{name:'U.S. Virgin Islands',nameLang:'U.S. Virgin Islands',code:'vi',dialCode:'+1-340',pattern:/^\d{7}$/},
{name:'Vanuatu',nameLang:'Vanuatu',code:'vu',dialCode:'+678',pattern:/^\d{6}$/},
{name:'Vatican City',nameLang:'Città del Vaticano',code:'va',dialCode:'+379',pattern:/^\d{4}$/},
{name:'Venezuela',nameLang:'Venezuela',code:'ve',dialCode:'+58',pattern:/^\d{10}$/},
{name:'Vietnam',nameLang:'Việt Nam',code:'vn',dialCode:'+84',pattern:/^\d{10}$/},
{name:'Wallis and Futuna',nameLang:'Wallis-et-Futuna',code:'wf',dialCode:'+681',pattern:/^\d{6}$/},
{name:'Western Sahara',nameLang:'الصحراء الغربية',code:'eh',dialCode:'+212',pattern:/^\d{9}$/},
{name:'Yemen',nameLang:'اليمن',code:'ye',dialCode:'+967',pattern:/^\d{9}$/},
{name:'Zambia',nameLang:'Zambia',code:'zm',dialCode:'+260',pattern:/^\d{10}$/},
{name:'Zimbabwe',nameLang:'Zimbabwe',code:'zw',dialCode:'+263',pattern:/^\d{9,10}$/}] as const;
type Country=typeof COUNTRIES[number];type TCode=Country['code'];type TDialCode=Country['dialCode'];
const PriorCountries:TCode[]=['in','us','ae','gb'];
export const GetCountries=(prioritySort:TCode[]=PriorCountries,filter?:{code?:TCode;dialCode?:TDialCode;search?:string}):ICountry[]=>{const prioritized=COUNTRIES.filter(c=>prioritySort.includes(c.code)).sort((a,b)=>prioritySort.indexOf(a.code)-prioritySort.indexOf(b.code));const rest=COUNTRIES.filter(c =>!prioritySort.includes(c.code));const countries=[...prioritized,...rest];if(filter?.code||filter?.dialCode){const matched=countries.find(c=>c.code===filter.code||c.dialCode===filter.dialCode);if(matched){return[matched];}else{filter.search=filter.code||filter.dialCode;}}if(filter?.search){const searchTerm=filter.search.toLowerCase();return countries.filter(c=>c.name.toLowerCase().includes(searchTerm)||c.nameLang.toLowerCase().includes(searchTerm)||c.code.toLowerCase().includes(searchTerm)||c.dialCode.toLowerCase().includes(searchTerm));}return countries;}
export const FlagPath=(countryCode:TCode,width:20|40|80|160|320|640=80)=>`https://flagcdn.com/w${width}/${countryCode}.png`;